config/routes.rb
Rails.application.routes.draw do
 devise_for :users
  root to: "homes#top"
  get '/home/about', to: "homes#about"


  
  resources :users
  
  resources :books do
  resource :favorites, only: [:create, :destroy]
  resources :book_comments, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

 validates :title, presence: true
 validates :body, presence: true, length: {maximum: 200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

 belongs_to :user
 belongs_to :book

 validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  attachment :profile_image

  validates :name, presence: true, length: { minimum: 2,maximum: 20}, uniqueness: true
  validates :introduction, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
  
  
  
  def after_sign_out_path_for(resource)
    root_path
  end



  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

 def create
  book = Book.find(params[:book_id])
  comment = current_user.book_comments.new(book_comment_params)
  comment.book_id = book.id
  comment.save
  redirect_to book_path(book)
 end

 def destroy
  BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
  redirect_to book_path(params[:book_id])
 end
 
  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

 before_action :authenticate_user!

 def index
  @book = Book.new
  @books = Book.all
  @user = current_user
 end

 def create
   @book = Book.new(book_params)
   @books = Book.all
   @book.user_id = current_user.id
   if @book.save
    flash[:notice2] = "You have created book successfully."
    redirect_to book_path(@book)
   else
   @user = current_user
    render :index
   end
 end

 def show
  @book_new = Book.new
  @book = Book.find(params[:id])
  @user = @book.user
  @book_comment = BookComment.new
 end

 def edit
  @book = Book.find(params[:id])
   if @book.user == current_user
    render "edit"
   else
    redirect_to books_path
   end

 end


 def update
   @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice3] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render 'edit'
    end
 end

 def destroy
  book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
 end



 private
 def book_params
   params.require(:book).permit(:title, :body)
 end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end

 
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :authenticate_user!

def show
 @book = Book.new
  @user = User.find(params[:id])
  @books  = @user.books

end

def index
  @users = User.all
  @user = current_user
  @book = Book.new
end




 def edit
  @user = User.find(params[:id])
  if @user == current_user
    render "edit"
  else
    redirect_to user_path(current_user)
  end
 end


 def update
    @user = User.find(params[:id])
    if  @user.update(user_params)
    flash[:notice1] = "You have updated user successfully."
    redirect_to user_path(@user.id)
    else
    render  'edit'
    end
 end

private
 def user_params
   params.require(:user).permit(:name, :introduction, :profile_image)
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<main>
  <% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
  <p id="notice"></p>
  <div class="container">
   <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	<%= form_with model: @book, local:true do |f| %>
      <div class="form-group"
      <label for="book_title">Title</label>
      <%= f.text_field :title %>
      </div>
      <div class="form-group">
      <label for="book_opinion">Opinion</label>
      <%= f.text_field :body %>
      </div>
      <div class="form-group">
      <%= f.submit "Update Book", class:"btn btn-secondary" %>
      </div>
      <% end %>

      <%=link_to "Show", book_path, class: "book_36933"  %>
      <%= "|" %>
      <%=link_to "Back", books_path, class: "back" %>
      </div>
    </div>
  </div>
  </main>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
 <% end %>

 <div class="container px-5 px-sm-0">
  <div class="row">
   <p id="notice"></p>
   <div class="col-md-3">
   <h2>User info</h2>
   <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', class:"exmaple-hoge", fallback: "no_image.jpg" %>
   <table class="table">
    <tbody>
    <tr></tr>
    <tr>
	   <th>name</th>
	   <th><%= @user.name %></th>
    </tr>
    <tr>
	   <th>introduction</th>
	   <th><%= @user.introduction %></th>
    </tr>
    </tbody>
   </table>


   <%= link_to "", edit_user_path(current_user) ,class:'btn btn-outline-secondary btn-block fas fa-user-cog',method: :get %>

   <h2 class="mt-3">New book</h2>
   <%= form_with model: @book, url: books_path, local:true do |f| %>
   <div class="form-group">
   <label for="book_title">Title</label>
    <%= f.text_field :title %>
   </div>
   <div class="form-group">
   <label for="book_opinion">Opinion</label>
    <%= f.text_field :body %>
   </div>
   <div class="form-group">
    <%= f.submit "Create Book" %>
   </div>
  <% end %>
 </div>

   <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
    <table class="table table-hover table-inverse">
    <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th></th>
      <th></th>
    </tr>
    </thead>

    <tbody>
     <% @books.each do |book| %>
     <tr>
     <td>
  		  <%= link_to  user_path(book) do %>
      <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', class:"exmaple-hoge", fallback: "no_image.jpg" %>
      <% end %>
      </td>
      <td> <%= link_to book.title, book_path(book.id), method: :get %></td>
      <td><%= book.body %></td>
      <td><% if book.favorited_by?(current_user) %>
          <p>
          <%= link_to book_favorites_path(book), method: :delete do %>
          <i class="fa fa-heart", style="color: red;", aria-hidden="true"></i><%= book.favorites.count %>
          <% end %>
          </p>
         <% else %>
          <p>
          <%= link_to book_favorites_path(book), method: :post do %>
          <i class="fa fa-heart", style="color: blue;", aria-hidden="true"></i><%= book.favorites.count %>
          <% end %>
          </p>
         <% end %></td>
      <td>コメント数:<%= book.book_comments.count %></td>
      </tr>
      <% end %>
     </tbody>
    </table>
   </div>
  </div>
 </div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
   <p id="notice"></p>
    <div class="col-md-3">
      <h2>User info</h2>
       <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>

       <table class="table">
        <tbody>
         <tr></tr>
         <tr>
	         <th>name</th>
	         <th><%= @user.name %></th>
         </tr>
         <tr>
	         <th>introduction</th>
	         <th><%= @user.introduction %></th>
         </tr>
        </tbody>
       </table>


    <div class="row">
     <%= link_to "", edit_user_path(@user) ,class:'btn btn-outline-secondary btn-block fas fa-user-cog',method: :get %>
    </div>
    <h2 class="mt-3">New book</h2>
    <%= form_with model: @book_new, url: books_path, method: :post, local:true do |f| %>
     <div class="form-group">
      <%= f.label :Title %>
      <%= f.text_field :title %>
     </div>
     <div class="form-group">
      <%= f.label :Opinion %>
      <%= f.text_field :body %>
     </div>
     <div class="form-group">
      <%= f.submit "Create Book" %>
     </div>
    <% end %>
   </div>

    <div class="col-md-8 offset-md-1">
  	  <h2>Book detail</h2>
  		 <table class="table">
  		  <tbody>
  		    <tr>
  		     <td>
  		      <%= link_to  user_path(@user) do %>
           <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %><br>
           <%= @user.name %> 
          <% end %>
         </td>
         <td><%= @book.title %></td>
         <td><%= @book.body %></td>
         <td>
         <% if @book.favorited_by?(current_user) %>
          <p>
          <%= link_to book_favorites_path(@book), method: :delete do %>
          <i class="fa fa-heart", style="color: red;", aria-hidden="true"></i><%= @book.favorites.count %> 
          <% end %>
          </p>
         <% else %>
          <p>
          <%= link_to book_favorites_path(@book), method: :post do %>
          <i class="fa fa-heart", style="color: blue;", aria-hidden="true"></i><%= @book.favorites.count %> 
          <% end %>
          </p>
         <% end %>
         </td>
         <td>コメント数:<%= @book.book_comments.count %></td>
         <% if @user.id == current_user.id %>
          <td><%=link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success" %></td>
          <td><%=link_to "Destroy", book_path(@book.id), class: "btn btn-sm btn-danger", method: :delete, data: { confirm: "本当に消しますか？" } %></td>
         <% end %>
        </tr>
      </tbody>
     </table>
     
     <div class="comments">
     <table class="table">
     <tbody>
      <% @book.book_comments.each do |book_comment| %>
      <tr>
       <td>
        <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %><br>
        <%= book_comment.user.name %></td>
       <td><%= book_comment.comment %></td>
       <% if book_comment.user == current_user %>
       <div class="comment-delete">
       <td><%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), class: "btn btn-sm btn-danger", method: :delete %></td>
       </div>
       <% end %>
       </tr>
       <% end %>
      </tbody>
     </table>
     </div>
     
     <div class="new-comment">
     <%= form_with(model:[@book, @book_comment], local: true) do |f| %>
     <%= f.text_area :comment, rows:'5' %>
     <%= f.submit "送信" %>
     <% end %>
     </div>
     
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<p id="notice"></p>
<div class="container">
 <div class="row">
 <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
</div>
</div>

app/views/homes/top.html.erb
 <p id="notice"></p>
 <div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class:"btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_notification.html.erb
<div class="Notification">
 <% flash.each do |key, value| %>
 <%= content_tag :div, value, class: key %>
 <% end %>
</div>

app/views/layouts/application.html.erb
<html>

  <head>
    <title>Bookers2Ver2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" href=“https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css” integrity=“sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk” crossorigin=“anonymous”>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src=“https://kit.fontawesome.com/b2da430b84.js” crossorigin=“anonymous”></script>
  </head>


  <body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto"


          <% if user_signed_in? %>
           <li><%= link_to"Home", user_path(current_user), class:"fas fa-home nav-link text-light", method: :get %> </li>
           <li><%= link_to"Users", users_path, class:"fas fa-users nav-link text-light", method: :get %> </li>
            <li><%= link_to"Books", books_path, class:"fas fa-book-open nav-link text-light", method: :get %> </li>
            <li>
           <%= link_to "logout", destroy_user_session_path, class: "fas fa-sign-out-alt nav-link text-light", method: :delete %>
           </li>
           <% else %>
           <li><%= link_to"Home", root_path, class:"fas fa-home nav-link text-light", method: :get %> </li>
          <li><%= link_to"About", home_about_path, class:"fas fa-link nav-link text-light", method: :get %> </li>
           <li>
           <%= link_to "sign up", new_user_registration_path, class: "fas fa-user-plus nav-link text-light" %>
           </li>
           <li>
           <%= link_to "login", new_user_session_path, class: "fas fa-sign-in-alt nav-link text-light" %>
         　 </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

  <main>
    <%= render 'layouts/notification' %>
    <%= yield %>
  </main>


  <footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>



</body>
</html>

app/views/users/edit.html.erb
 <% if @user.errors.any? %>
  <%= @user.errors.count %>件のerrorが発生しました
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
  <p id="notice"></p>
  <div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>




  　　　<%= form_with model: @user, local:true do |f| %>
   　　<div class="form-group">
    　<label for="user_name">Name</label>
    　<%= f.text_field :name %>
   　　</div>
   　　<div class="form-group">
   　　<label for="user_image">Image</label>
   　　 <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
   　　</di>
   　　<div class="form-group">
   　　<label for="user_introduction">introduction</label>
    　<%= f.text_area :introduction %>
  　　　 </div>
   　　<div class="form-group">
    　<%= f.submit  "Update User", class:"btn btn-secondary" %>
    　</div>
  　　　<% end %>
</form>  </div>
</div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
   <p id="notice"></p>
    <div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
      <table class="table">
       <tbody>
        <tr></tr>
        <tr>
   	     <th>name</th>
   	     <th><%= @user.name %></th>
        </tr>
        <tr>
   	     <th>introduction</th>
   	     <th><%= @user.introduction %></th>
        </tr>
       </tbody>
      </table>

      
       <%= link_to "", edit_user_path(@user) ,class:'btn btn-outline-secondary btn-block fas fa-user-cog',method: :get %>
　　　
  　　　<h2 class="mt-3">New book</h2>
  　　　<%= form_with model: @book, url: books_path, local:true do |f| %>
   　 　<div class="form-group">
    　  <label for="book_title">Title</label>
    　  <%= f.text_field :title %>
   　 　</div>
   　 　<div class="form-group">
   　 　<label for="book_opinion">Opinion</label>
    　  <%= f.text_area :body %>
  　 　　 </div>
   　 　<div class="form-group">
     　 <%= f.submit "Create Book" %>
     　</div>
  　　　<% end %>
  　</div>


    <div class="col-md-8 offset-md-1">
     <h2>Users</h2>
     <table class="table">
      <thead>
       <tr>
       <th>image</th>
       <th>name</th>
       <th></th>
       </tr>
      </thead>
      
      <tbody>
      <% @users.each do |user| %>
       <tr>
       <td>
       <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
       </td>
       <td><%= user.name %></td>
       <td><%= link_to"Show", user_path(user) %> </td>
       </tr>
       <% end %>
       </tbody>
     </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
       <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', class:"exmaple-hoge", fallback: "no_image.jpg" %>
      <table class="table">
      <tbody><tr></tr>
      <tr>
	     <th>name</th>
	     <th><%= @user.name %></th>
      </tr>
      <tr>
	     <th>introduction</th>
	     <th><%= @user.introduction %></th>
      </tr>
      </tbody>
      </table>


   <div class="row">
    <%= link_to "", edit_user_path(@user) ,class:'btn btn-outline-secondary btn-block fas fa-user-cog',method: :get %>
　</div>
　<h2 class="mt-3">New book</h2>
  <%= form_with model:@book, url: books_path, local:true do |f| %>
　<div class="form-group"
   <label for="book_title">Title</label>
   <%= f.text_field :title %>
　</div>
　<div class="form-group">
 　<label for="book_opinion">Opinion</label>
   <%= f.text_area :body %>
  </div>
　<div class="form-group">
   <%= f.submit "Create Book" %>
  </div>
  <% end %>
 </div>

  <div class="col-md-8 offset-md-1">
   <h2>Books</h2>
   <table class="table table-hover table-inverse">
   <thead>
   <tr>
   <th></th>
   <th>Title</th>
   <th>Opinion</th>
   <th></th>
   <th></th>
　 </tr>
　 </thead>
　 
　 <tbody>
   <% @books.each do |book| %>
    <tr>
    <td><%= link_to  user_path(@user) do %>
    <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', class:"exmaple-hoge", fallback: "no_image.jpg" %>
    <% end %>
    </td>
    <td><%= link_to book.title, book_path(book.id) %></td>
    <td><%= book.body %></td>
    <td><% if book.favorited_by?(current_user) %>
          <p>
          <%= link_to book_favorites_path(book), method: :delete do %>
          <i class="fa fa-heart", style="color: red;", aria-hidden="true"></i><%= book.favorites.count %>
          <% end %>
          </p>
         <% else %>
          <p>
          <%= link_to book_favorites_path(book), method: :post do %>
          <i class="fa fa-heart", style="color: blue;", aria-hidden="true"></i><%= book.favorites.count %>
          <% end %>
          </p>
         <% end %></td>
      <td>コメント数:<%= book.book_comments.count %></td>
    </tr>
    <% end %>
 　</tbody>
　 </table>
　</div>
 </div>
</div>